export const theme = {
  colors: {
    accent: "#6366f1",
    accentBg: "#3a3a5a",
    accentBgHover: "#454565",
    accentLight: "#a78bfa",
    background: "#1e1e1e",
    black: "#000",
    border: "#333",
    borderActive: "#60a5fa",
    borderInput: "#444",
    borderSelected: "#6366f1",
    error: "#ef4444",
    errorBg: "#3a1a1a",
    errorBgHover: "#4a2020",
    gqlMutation: { bg: "#3a1e5f", color: "#a78bfa" },
    gqlQuery: { bg: "#1e3a5f", color: "#60a5fa" },
    graphql: "#a78bfa",
    graphqlBg: "#2d1b4e",
    info: "#3b82f6",
    methodDelete: { bg: "#5f1e1e", color: "#ef4444" },
    methodGet: { bg: "#1e3a5f", color: "#60a5fa" },
    methodPatch: { bg: "#3a1e5f", color: "#a78bfa" },
    methodPost: { bg: "#1e5f3a", color: "#4ade80" },
    methodPut: { bg: "#5f3a1e", color: "#fb923c" },
    rest: "#60a5fa",
    restBg: "#1b2e4e",
    success: "#4ade80",
    successBg: "#1a3a1a",
    successBgHover: "#1f4a1f",
    surface: "#1a1a1a",
    surfaceGroupHeader: "#1e1e2e",
    surfaceGroupHeaderHover: "#262640",
    surfaceHover: "#2a2a2a",
    surfaceHoverStrong: "#333",
    surfaceSelected: "#2a2a3a",
    textDisabled: "#ccc",
    textDimmed: "#555",
    textLabel: "#a0a0a0",
    textMuted: "#666",
    textPrimary: "#e0e0e0",
    textSecondary: "#888",
    toggleOff: "#444",
    toggleOffHover: "#555",
    warning: "#facc15",
    warningBg: "#3a3a1a",
    white: "#fff",
  },

  fontFamily: {
    mono: 'ui-monospace, "Cascadia Code", "Source Code Pro", Menlo, Consolas, monospace',
    sans: "system-ui, -apple-system, sans-serif",
  },

  fontSize: {
    base: "12px",
    lg: "13px",
    md: "11px",
    sm: "10px",
    xl: "14px",
    xs: "9px",
  },

  radius: {
    lg: "6px",
    md: "4px",
    pill: "10px",
    round: "50%",
    sm: "3px",
  },

  spacing: {
    lg: "8px",
    md: "6px",
    sm: "4px",
    xl: "12px",
    xs: "2px",
  },
} as const;
