/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PlaygroundRouteRouteImport } from './routes/playground/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as PlaygroundApolloRouteImport } from './routes/playground/apollo'
import { Route as PlaygroundFetchRouteImport } from './routes/playground/fetch'
import { Route as PlaygroundQueryRouteImport } from './routes/playground/query'
import { Route as PlaygroundRtkQueryRouteImport } from './routes/playground/rtk-query'
import { Route as PlaygroundSwrRouteImport } from './routes/playground/swr'
import { Route as PlaygroundUrqlRouteImport } from './routes/playground/urql'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundApolloRoute = PlaygroundApolloRouteImport.update({
  id: '/apollo',
  path: '/apollo',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundFetchRoute = PlaygroundFetchRouteImport.update({
  id: '/fetch',
  path: '/fetch',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundQueryRoute = PlaygroundQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundRtkQueryRoute = PlaygroundRtkQueryRouteImport.update({
  id: '/rtk-query',
  path: '/rtk-query',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundSwrRoute = PlaygroundSwrRouteImport.update({
  id: '/swr',
  path: '/swr',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundUrqlRoute = PlaygroundUrqlRouteImport.update({
  id: '/urql',
  path: '/urql',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/playground/apollo': typeof PlaygroundApolloRoute
  '/playground/fetch': typeof PlaygroundFetchRoute
  '/playground/query': typeof PlaygroundQueryRoute
  '/playground/rtk-query': typeof PlaygroundRtkQueryRoute
  '/playground/swr': typeof PlaygroundSwrRoute
  '/playground/urql': typeof PlaygroundUrqlRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/playground/apollo': typeof PlaygroundApolloRoute
  '/playground/fetch': typeof PlaygroundFetchRoute
  '/playground/query': typeof PlaygroundQueryRoute
  '/playground/rtk-query': typeof PlaygroundRtkQueryRoute
  '/playground/swr': typeof PlaygroundSwrRoute
  '/playground/urql': typeof PlaygroundUrqlRoute
  '/playground': typeof PlaygroundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/playground/apollo': typeof PlaygroundApolloRoute
  '/playground/fetch': typeof PlaygroundFetchRoute
  '/playground/query': typeof PlaygroundQueryRoute
  '/playground/rtk-query': typeof PlaygroundRtkQueryRoute
  '/playground/swr': typeof PlaygroundSwrRoute
  '/playground/urql': typeof PlaygroundUrqlRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/about'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/playground/apollo'
    | '/playground/fetch'
    | '/playground/query'
    | '/playground/rtk-query'
    | '/playground/swr'
    | '/playground/urql'
    | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/playground/apollo'
    | '/playground/fetch'
    | '/playground/query'
    | '/playground/rtk-query'
    | '/playground/swr'
    | '/playground/urql'
    | '/playground'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/about'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/playground/apollo'
    | '/playground/fetch'
    | '/playground/query'
    | '/playground/rtk-query'
    | '/playground/swr'
    | '/playground/urql'
    | '/playground/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRouteRoute: typeof PlaygroundRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/apollo': {
      id: '/playground/apollo'
      path: '/apollo'
      fullPath: '/playground/apollo'
      preLoaderRoute: typeof PlaygroundApolloRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/fetch': {
      id: '/playground/fetch'
      path: '/fetch'
      fullPath: '/playground/fetch'
      preLoaderRoute: typeof PlaygroundFetchRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/query': {
      id: '/playground/query'
      path: '/query'
      fullPath: '/playground/query'
      preLoaderRoute: typeof PlaygroundQueryRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/rtk-query': {
      id: '/playground/rtk-query'
      path: '/rtk-query'
      fullPath: '/playground/rtk-query'
      preLoaderRoute: typeof PlaygroundRtkQueryRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/swr': {
      id: '/playground/swr'
      path: '/swr'
      fullPath: '/playground/swr'
      preLoaderRoute: typeof PlaygroundSwrRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/urql': {
      id: '/playground/urql'
      path: '/urql'
      fullPath: '/playground/urql'
      preLoaderRoute: typeof PlaygroundUrqlRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
  }
}

interface PlaygroundRouteRouteChildren {
  PlaygroundApolloRoute: typeof PlaygroundApolloRoute
  PlaygroundFetchRoute: typeof PlaygroundFetchRoute
  PlaygroundQueryRoute: typeof PlaygroundQueryRoute
  PlaygroundRtkQueryRoute: typeof PlaygroundRtkQueryRoute
  PlaygroundSwrRoute: typeof PlaygroundSwrRoute
  PlaygroundUrqlRoute: typeof PlaygroundUrqlRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

const PlaygroundRouteRouteChildren: PlaygroundRouteRouteChildren = {
  PlaygroundApolloRoute: PlaygroundApolloRoute,
  PlaygroundFetchRoute: PlaygroundFetchRoute,
  PlaygroundQueryRoute: PlaygroundQueryRoute,
  PlaygroundRtkQueryRoute: PlaygroundRtkQueryRoute,
  PlaygroundSwrRoute: PlaygroundSwrRoute,
  PlaygroundUrqlRoute: PlaygroundUrqlRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}

const PlaygroundRouteRouteWithChildren = PlaygroundRouteRoute._addFileChildren(
  PlaygroundRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRouteRoute: PlaygroundRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
